### ISSUE TITLE
Use existing community maintained charts

### ISSUE THREAD

**Issue by bclermont** [jfelten/gitea-helm-chart#18]
There is already community maintained helm charts for:

- [memcache](https://github.com/helm/charts/tree/master/stable/memcached)
- [postgresql](https://github.com/helm/charts/tree/master/stable/postgresql)

you shouldn't re-implemented these by using [requirements](https://docs.helm.sh/developing_charts/#chart-dependencies)

**Comment by jfelten** [comment]
That was a conscious design decision  I made for the following reasons:

 * I was aiming for an appliance like deployment to minimize config. Helm install should just work out of the box with no custom values.
 * simplicity - no external dependencies other than the chart values.  Integration with other deployments can be painful.  The helm dependency mechanism is nice and works, but adds complexity, decreases robustness and adds operational cost in my opinion. 
 * control of images - not dependent on what the community chooses 
 * more control of how it is set up.  The charts for memcache/redis are complex stateful set vs deployments.  All I wanted was a simple cache container.

That being said I ended up making the in pod db optional because db storage really should be an end user choice.  If people want they can disable the in pod db and set up whatever db they see fit.  If this is not clear from the documentation I can do a PR to address it

The same could be said of memcache, but I kind of like the way it is.  If enough people complain about this I could easily make a PR to address to add an optional flag.

Contributed PRs are always welcome.

**Comment by bclermont** [comment]
> I was aiming for an appliance like deployment to minimize config. Helm install should just work out of the box with no custom values.

at the end there is much more logic and complexity.

plus, as postgresql and redis are running as containers and not pod, and the ports aren't exposed, there is no way to monitor those 2 services with prometheus.

> control of images - not dependent on what the community chooses

you can lock requirements to a specific version

> more control of how it is set up.  The charts for memcache/redis are complex stateful set vs deployments.  All I wanted was a simple cache container.

you could just have use `memory` cache and drop redis.

> I could easily make a PR to address to add an optional flag.

for me, it's fine, I built a new chart from scratch that just implement the gitea specifics

**Comment by jpds** [comment]
I also bumped into this looking at this chart. The chart at https://github.com/isaron/gitea-kubernetes/tree/master/helm does the Right Thing with using subcharts.
